can_interface: can0
bitrate: 500000

rtr_ids:
  - id: 0x100
    freq: 20.0  # Frequency in Hz
    variables:
      - name: adc_ch1
        type: int32
      - name: adc_ch2
        type: int32
    

  
    